import Footer from 'components/Footer';
import Head from 'next/head';
import Banner from 'sections/Banner';
import Benefits from 'sections/Benefits';
import Faq from 'sections/Faq';
import Sell from 'sections/Sell';
import Testimonies from 'sections/Testimonies';

const Home = () => {
  return (
    <>
      <Head>
        <title>Rocket Wins</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Banner />
      <Benefits />
      <Testimonies />
      <Faq />
      <Sell />
      <Footer />
    </>
  );
};

export default Home;
