import { Flex } from '@chakra-ui/react';
import Carousel from 'components/Carousel';
import Container from 'components/Container';
import Seller from 'components/Seller';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container pt={10}>
        <Flex w="50%">
          <Seller />
        </Flex>
        <Flex w="50%">
          <Carousel />
        </Flex>
      </Container>
    </>
  );
}
