import Head from 'next/head';
import Banner from 'sections/Banner';
import Benefits from 'sections/Benefits';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Banner />
      <Benefits />
    </>
  );
};

export default Home;
